name: Deploy HTML Files to AppService - CMST385

on:

  push:

	branche:

	  - main

jobs:

  build-and-deploy:

	runs-on: windows-latest

	 steps:

	- uses: actions/checkout@master

	- name: Deploy to Azure Web App

	  uses: azure/webapps-deploy@v1

	  with:

		app-name: 'CMST385-jguthrie12'

		slot-name: 'production'

		publish-profile: ${{ secrets.CMST385_JGUTHRIE12 }}
